services:
  # 1. Le Backend (Serveur Flask)
  - type: web
    name: onction-ministry-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir backend/src app:app"
    envVars:
      - key: DATABASE_URL
        sync: false

  # 2. Le Frontend (Le site visuel HTML)
  - type: web
    name: onction-ministry-frontend
    runtime: static
    publishBy: Frontend